### ISSUE TITLE
Receiving "expected x destination arguments in Scan, not y" with functioning SQL query

### ISSUE THREAD

**Issue by hae2** [zensqlmonitor/influxdb-sqlserver#10]
Hi,

To elaborate on the issue, I migrated our fully functioning SQL code/queries from an existing Visual Studio project and received the error in the title. When the query is run directly against the database, it works fine. Because of this, I am led to believe that this is may be a code issue rather than the SQL query itself. The query can be provided if needed.

Thanks a bunch!

**Comment by zensqlmonitor** [comment]
Hi, you have to format result in an inline format, as defined in the provided T-SQL files.
You can post your select clause here I will tell you what's wrong.

**Comment by hae2** [comment]
Hi, here is what the select clause looks like -

SELECT
      @collect_dt_min [collect_dt_min]
    , @collect_dt_max [collect_dt_max]
    , @availability_last_restart [availability_last_restart] 
    , @availability_sample_count_instance [availability_sample_count_instance]
    , @availability_sample_count_disk [availability_sample_count_disk]
    , @availability_sample_count_network [availability_sample_count_network]
    , @availability_last_sample_instance [availability_last_sample_instance]
    , @availability_last_sample_disk [availability_last_sample_disk]
    , @availability_last_sample_network [availability_last_sample_network]
    , @cpu_host_avg [cpu_host_avg]
    , @cpu_host_max [cpu_host_max]
    , @cpu_host_change [cpu_host_change] 
    , @cpu_host_to_instance_delta [cpu_host_to_instance_delta] 
    , @memory_bchr_avg [memory_bchr_avg] 
    , @memory_bchr_min [memory_bchr_min]
    , @memory_bchr_low_count [memory_bchr_low_count] 
    , @memory_ple_avg [memory_ple_avg] 
    , @memory_ple_low_count [memory_ple_low_count] 
    , @memory_ple_bchr_low_count [memory_ple_bhcr_low_count] 
    , @tempdb_data_free_percent [tempdb_data_free_percent] 
    , @tempdb_log_free_percent [tempdb_log_free_percent]  
    , @blocking_count [blocking_count] 
    , @blocking_longest_event [blocking_longest_event] 
    , @deadlock_count [deadlock_count] 
    , @disk_read_ms_max [disk_read_ms_max]
    , @disk_read_ms_avg [disk_read_ms_avg]
    , @disk_write_ms_max [disk_write_ms_max]
    , @disk_write_ms_avg [disk_write_ms_avg]
    , @network_utilization_percent_received_avg [network_utilization_percent_received_avg]
    , @network_utilization_percent_received_max [network_utilization_percent_received_max]
    , @network_utilization_high_count_received [network_utilization_high_count_received] 
    , @network_utilization_percent_sent_avg [network_utilization_percent_sent_avg]
    , @network_utilization_percent_sent_max [network_utilization_percent_sent_max]
    , @network_utilization_high_count_sent [network_utilization_high_count_sent]
    , (SELECT MAX(counter_state) FROM #state WHERE subsystem = 'availability') [availability_state]
    , (SELECT MAX(counter_state) FROM #state WHERE subsystem = 'cpu') [cpu_state]
    , (SELECT MAX(counter_state) FROM #state WHERE subsystem = 'memory') [memory_state]
    , (SELECT MAX(counter_state) FROM #state WHERE subsystem = 'tempdb') [tempdb_state]
    , (SELECT MAX(counter_state) FROM #state WHERE subsystem = 'concurrency') [contention_state]
    , (SELECT MAX(counter_state) FROM #state WHERE subsystem = 'disk') [disk_state]
    , (SELECT MAX(counter_state) FROM #state WHERE subsystem = 'network') [network_state]
    , availability_last_restart_state
    , availability_last_sample_instance_state
    , availability_last_sample_disk_state
    , availability_last_sample_network_state
    , availability_sample_count_instance_state
    , availability_sample_count_disk_state
    , availability_sample_count_network_state
    , cpu_host_avg_state
    , cpu_host_max_state
    , cpu_host_change_state
    , cpu_host_to_instance_delta_state
    , memory_bchr_avg_state
    , memory_bchr_min_state
    , memory_bchr_low_count_state
    , memory_ple_avg_state
    , memory_ple_low_count_state
    , memory_ple_bchr_low_count_state
    , tempdb_data_free_percent_state
    , tempdb_log_free_percent_state
    , blocking_count_state
    , blocking_longest_event_state
    , deadlock_count_state
    , disk_read_ms_max_state
    , disk_read_ms_avg_state
    , disk_write_ms_max_state
    , disk_write_ms_avg_state
    , disk_space_free_state
    , network_utilization_percent_received_avg_state
    , network_utilization_high_count_received_state
    , network_utilization_percent_sent_avg_state
    , network_utilization_high_count_sent_state

FROM (SELECT counter_name, counter_state FROM #state) cte 
    PIVOT(MAX(counter_state) 
          FOR counter_name IN (availability_last_restart_state
            , availability_last_sample_instance_state
            , availability_last_sample_disk_state
            , availability_last_sample_network_state
            , availability_sample_count_instance_state
            , availability_sample_count_disk_state
            , availability_sample_count_network_state
            , cpu_host_avg_state
            , cpu_host_max_state
            , cpu_host_change_state
            , cpu_host_to_instance_delta_state
            , memory_bchr_avg_state
            , memory_bchr_min_state
            , memory_bchr_low_count_state
            , memory_ple_avg_state
            , memory_ple_low_count_state
            , memory_ple_bchr_low_count_state
            , tempdb_data_free_percent_state
            , tempdb_log_free_percent_state
            , blocking_count_state
            , blocking_longest_event_state
            , deadlock_count_state
            , disk_read_ms_max_state
            , disk_read_ms_avg_state
            , disk_write_ms_max_state
            , disk_write_ms_avg_state
            , disk_space_free_state
            , network_utilization_percent_received_avg_state
            , network_utilization_high_count_received_state
            , network_utilization_percent_sent_avg_state
            , network_utilization_high_count_sent_state)) AS PVTTable

This piece is also at the very end of the whole code.

**Comment by zensqlmonitor** [comment]
As specified result has to be formatted in an inline format.
