### ISSUE TITLE
SQL Instances not supported

### ISSUE THREAD

**Issue by OO00dougal00OO** [zensqlmonitor/influxdb-sqlserver#11]
Hi, there does not seem to be any option to specify named SQL instances in the configuration. Am i missing something obvious as each time i try to add a named instance into the config file i get an "Invalid escape character" or it just does not connect. Configurations i have tried so far are below.

  [servers.servername]
  ip = "servername\instancename" 
  port = 1433       
  username="someuser"
  password="somepassword"

gives "invalid Escape character"

  [servers.servername]
  ip = "servername\\instancename" 
  port = 1433       
  username="someuser"
  password="somepassword"

runs but gives the following output 

2016/12/11 22:10:14 [log.go:299 Error()] [E] Error while executing script%!(EXTRA *errors.errorString=Login error: read tcp #.#.#.#:59711->#.#.#.#:59044: wsarecv: An existing connection was forcibly closed by the remote host.)
2016/12/11 22:10:14 [log.go:299 Error()] [E] Error while executing script%!(EXTRA *errors.errorString=Login error: read tcp #.#.#.#:59709->#.#.#.#:59044: wsarecv: An existing connection was forcibly closed by the remote host.)

  [servers.servername\instancename]
  ip = "servername or ip address" 
  port = 1433       
  username="someuser"
  password="somepassword"

gives "Bare keys cannot contain '\\'"

If you need any more info please let me know.

Thanks

**Comment by zensqlmonitor** [comment]
Hi,
you have 2 choices:
- [servers.servername\instancename] -> replace the backslash with an underscore (_)
- double the backslash in the ip
