### ISSUE TITLE
Login error - read: connection reset by peer

### ISSUE THREAD

**Issue by jsantanajr** [zensqlmonitor/influxdb-sqlserver#12]
Hi,

I configured the script according to git, but when you start is returned:

[log.go:299 Error()] [E] Error while executing script%!(EXTRA *errors.errorString=Login error: read tcp SERVER1:49466->SERVERDEST:1433: read: connection reset by peer)

By telnet and tsql, the connections is fine to port 1433 with same user and password, but if start by:

go run influxdb-sqlserver.go &

Besides the errors, nothing arrives in the bd (verifying profiler).

Do you have any tips?

Tks

**Comment by jsantanajr** [comment]
This is my file .conf, i change the users and servers tags.

[influxdb-sqlserver.zip](https://github.com/zensqlmonitor/influxdb-sqlserver/files/702477/influxdb-sqlserver.zip)

Tks

**Comment by zensqlmonitor** [comment]
Hi,

Doesn't look like an issue with SQL Server but more often with firewall.
Also, check you go version and, have a look there if it is solved your problem:
https://github.com/denisenkom/go-mssqldb/issues/48

Regards

**Comment by jsantanajr** [comment]
Hi,

Thanks for your help, i've tried with SQL SERVER 2012 and works fine, except this error:

 [log.go:299 Error()] [E] Error while executing script%!(EXTRA *errors.errorString=mssql: There is insufficient result space to convert a money value to int.)

I can adjust a conversion in the script, or is it something else?

Regards

**Comment by jsantanajr** [comment]
PS:

I believe that due to this error, the Dashboard's:

- SQL Server Activity
- Database Activity
- Buffer Cache - Disk

And others KPI's returning this message: No datapoints

Many thanks for your attention

**Comment by jsantanajr** [comment]
Hi Z,

I found this fix:

https://github.com/influxdata/telegraf/pull/1083/commits/93f5b8cc4aaad22e8c2195a24c97884e5a5e5787

All dashboards are working now. Many thanks for your attention and congratulations for this awesome project.

Regards
