### ISSUE TITLE
package.sh fails to build

### ISSUE THREAD

**Issue by nmat** [zensqlmonitor/influxdb-sqlserver#14]
I am getting error on trying to build influxdb-sqlserver using: package.sh

The issue is that it can't copy the T-SQL scripts.

Starting packaging process, version: 99d1e87

GOPATH (/usr/local/go) looks sane, using /usr/local/go for installation.
Building...
Copying configuration file...
Replacing parameters in configuration file...
Build completed successfully.
influxdb-sqlserver copied to /tmp/tmp.3cHmDEGpi1/opt/influxdb-sqlserver/versions/99d1e87
influxdb-sqlserver.conf copied to /tmp/tmp.3cHmDEGpi1/etc/influxdb-sqlserver
Failed to copy T-SQL scripts to packaging directory -- aborting.

Not sure why. I install all of go including the influxdb-sqlserver system under /usr/local/go/

Then tried running the package.sh from there but without any good result.

Is it possible that a .deb for ubuntu can be released on the github page here?

**Comment by zensqlmonitor** [comment]
Correction made for debian package.
Anyway this project has to be completly redesigned...
