### ISSUE TITLE
Avg Disk IO wait time has no datapoints

### ISSUE THREAD

**Issue by andrew-barringer** [zensqlmonitor/influxdb-sqlserver#2]
See attached image.
![screen shot 2016-01-20 at 1 14 58 pm](https://cloud.githubusercontent.com/assets/846034/12459865/e4cfb728-bf7e-11e5-854b-060c75a05cf8.png)

**Comment by zensqlmonitor** [comment]
Just remove it from the dashboard. 
This metric is no more collected.
