### ISSUE TITLE
Trying to build application

### ISSUE THREAD

**Issue by ragesaq** [zensqlmonitor/influxdb-sqlserver#5]
I'm able to make the application run without issue, but the package.sh / final build details seem a little too thin for me to figure out or they don't work.
When I run package.sh I get

Starting packaging process, version: 1b53769

GOPATH (/usr/local/go/work) looks sane, using /usr/local/go/work for installation.
Building...
Copying configuration file...
Replacing parameters in configuration file...
Build completed successfully.
cp: cannot stat `/usr/local/go/work/bin/influxdb-sqlserver': No such file or directory
Failed to copy binaries to packaging directory -- aborting.

Any hints? This thing is really neat!

**Comment by zensqlmonitor** [comment]
Have you tried a 'go build' first ?

**Comment by ragesaq** [comment]
Yeah, I did that, and if I copy the sqlscripts directory to $GOPATH/bin it works fine.
However, the package.sh is just one problem after another, still haven't worked through them all to get a working deb. I was able to get package.sh to build but the deb doesn't quite work right. I'm on Ubuntu but my debian system has similar problems
My list of things I have figured out how to fix:
1: init.sh from /scripts has extra arguements that don't work, like -pidfile $pidfile AFTER --exec and -configdirector. The app professes to only take -config
2: Missing packages directory in /github.com/zensqlmonitor/influxdb-sqlserver/
3: package.sh line 260/261. Something about this doesn't seem to execute properly despite it copying the files correctly.
4: package.sh line 321 bombs on making the rpm

**Comment by ragesaq** [comment]
Found one of the remaining issues
in config/config.go the DefaultSqlScriptPath string = should not be "sqlscripts/" it should be "/usr/local/influxdb-sqlserver/sqlscripts/"
After this and my other identified fixes, I can go build and then execute package.sh. and use that .deb on another system successfully. The init script runs correctly, but status and stop/restart don't work.

**Comment by zensqlmonitor** [comment]
Sounds good. The reason I have not informed about this part of work is that it was not tested on all platforms. It worked on RHEL when I made it.
Can you propose your modifications ?
Regarding the init script, can you supply the logs ?
