### ISSUE TITLE
Unable to connect to SQL Server with Server as : Hostname\instancename

### ISSUE THREAD

**Issue by parabinda** [zensqlmonitor/influxdb-sqlserver#9]
Hi,
Thank you for making Grafana work for SQL server.

I am having an issue with Building with go.

**my relevant configuration:**
I gave my SQL Instance name as below
  [servers.DL-DZ83D72\SQLEXPRESS]
  ip = "192.168.43.12" 
  port = 49164       
## Issue while running

C:\Users\asahoo\work\src\github.com\zensqlmonitor\influxdb-sqlserver>go run infl
uxdb-sqlserver.go &
panic: Near line 42 (last key parsed 'servers'): Bare keys cannot contain '\'.

goroutine 1 [running]:
panic(0x668780, 0xc042482a30)
        C:/Go/src/runtime/panic.go:500 +0x1af
main.main()
        C:/Users/asahoo/work/src/github.com/zensqlmonitor/influxdb-sqlserver/inf
luxdb-sqlserver.go:302 +0x791
## exit status 2

Please let me know, how I can connect Database using a SQLEXPRESS instance.

Thank you

Sincerely yours
Arabinda
parabinda@gmail.com

**Comment by zensqlmonitor** [comment]
Hi,

[servers.DL-DZ83D72\SQLEXPRESS] is your instance name in the config file, it is not used for the connection string. It seems the TOML parser doesn't like the backslash.
Please use an underscore instead as [servers.DL-DZ83D72_SQLEXPRESS]

To connect to a SQLEXPRESS instance, just define the IP and port as specified.

Regards,
Z
